# Generated by Django 6.0.1 on 2026-01-27 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='download',
            name='quality',
            field=models.CharField(default='medium', max_length=10),
        ),
    ]
